package com.wpmac.androidnougatframework.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wpmac.androidnougatframework.db.ExCompany;
import com.wpmac.androidnougatframework.db.Express;

import com.wpmac.androidnougatframework.db.ExCompanyDao;
import com.wpmac.androidnougatframework.db.ExpressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exCompanyDaoConfig;
    private final DaoConfig expressDaoConfig;

    private final ExCompanyDao exCompanyDao;
    private final ExpressDao expressDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exCompanyDaoConfig = daoConfigMap.get(ExCompanyDao.class).clone();
        exCompanyDaoConfig.initIdentityScope(type);

        expressDaoConfig = daoConfigMap.get(ExpressDao.class).clone();
        expressDaoConfig.initIdentityScope(type);

        exCompanyDao = new ExCompanyDao(exCompanyDaoConfig, this);
        expressDao = new ExpressDao(expressDaoConfig, this);

        registerDao(ExCompany.class, exCompanyDao);
        registerDao(Express.class, expressDao);
    }
    
    public void clear() {
        exCompanyDaoConfig.clearIdentityScope();
        expressDaoConfig.clearIdentityScope();
    }

    public ExCompanyDao getExCompanyDao() {
        return exCompanyDao;
    }

    public ExpressDao getExpressDao() {
        return expressDao;
    }

}
